# Generated by Django 3.1.4 on 2021-01-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_company_massrapidtransityear'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaipeiStationInOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('io_class', models.CharField(max_length=10)),
                ('io_amount', models.PositiveIntegerField()),
            ],
        ),
    ]
