# Generated by Django 3.1.4 on 2021-01-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_taipeistationinout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taipeistationinout',
            name='io_class',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='taipeistationinout',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
